### ISSUE TITLE
all tests pass after requirements for first tests are met

### ISSUE THREAD

**Issue by jessicasalmon** [foundersandcoders/ws-password-management#16] opened 2017-08-07 11:22 UTC
#15 fixed the issue of tests passing before any code to make the functions pass had been written

Now tests initially fail, but once one test passes, the following two tests also pass (even if no code has been written in the `comparePasswords` function).

**Comment by matthewdking** [comment] 2017-08-13 07:59
For reference this is the code that will pass all the tests
```javascript
const hashPassword = (password, callback) => {
  bcrypt.genSalt(10, function(err, salt) {
    bcrypt.hash(password, salt, function(err, hash) {
      callback(err, hash);
    })
  })
};
```

**Comment by Karyum** [comment] 2017-08-13 08:21
Also when you pass all the tests the first time and then comment out your code it still passes
![screenshot from 2017-08-13 11-19-59](https://user-images.githubusercontent.com/24195641/29248156-7b27871c-8019-11e7-8a19-05d812fdf876.png)

**Comment by eliasmalik** [comment] 2017-08-17 18:39
I cannot reproduce any of this behaviour since #18 has been merged. Please close if you are satisfied @bo-bok

**Closed as completed** 2017-11-12 20:13 UTC
Labels: bug
